[package]
name = "warmup-f24"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.7", features = ["json", "blocking"] } 
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tungstenite = { version = "0.24.0", features = ["native-tls"] }
